### ISSUE TITLE
Viewing nothing when using Kong Ingress

### ISSUE THREAD

**Issue by cronventis** [yesinteractive/kong-map#9]
I was trying to visualize my cluster. we are using KongIngress and the cluster was added propperly..
Even when klicking on edit (view mode only) the konfig gets loaded and all services are listed..
But I can only see the Kong Logo in the "view" part... No errors anywhere..

**Comment by nikirago** [comment]
Hi, you have exposed the admin api of the controller/gateway? What version of Kong Ingress controller are you using?  Are you saying the config is showing properly in declarative viewer but not the map? If so, there is something in the map that is breaking the javascript?  What does the javascript console say in the browser? Can you share the resulting HTML of the map view (minus anything that would be private)

**Comment by cronventis** [comment]
1. What exactly do you mean by controller/gateway?
2. KongIngress = kong:2.2.1-alpine
3. That is correct
4. There are no js errors in the console
![image](https://user-images.githubusercontent.com/60728024/105007961-eb765000-5a38-11eb-80b7-11e66d90b5ae.png)
5. The canvas element is there, but except the monkey.. There is nothing else:
![image](https://user-images.githubusercontent.com/60728024/105007864-cda8eb00-5a38-11eb-8343-52d2f01c20f3.png)

**Comment by nikirago** [comment]
One last thing, can you share the kongmap cluster config json (minus sensitive data)?  Happy to jump on a zoom to help live.

**Comment by nikirago** [comment]
This could also be related to an issue w/ the new vis-network version that was released that broke some elements of the map. Will be updating the docker image in the next 24 hours to fix.

**Comment by nikirago** [comment]
Hi @cronventis .  Can you pull the latest image from dockerhub and verify if the problem is now resolved related to https://github.com/yesinteractive/kong-map/issues/10?

**Comment by cronventis** [comment]
Nope, still not working.
how would you like to get in contact so you can take a closer look?

**Comment by nikirago** [comment]
If you are not comfortable leaving your email here, please do so on the contact form on https://www.yes-interactive.com/ and reference this issue and I will get back to you via email. we can schedule a zoom call to figure out what's going on.

Is the admin API generating content? meaning, are there are the /routes and /services endpoints showing any data? It looks like nothing is being returned (ie, if there is nothing configured in Kong as far as ingress rules/routes and services then the map will just show the Kong logo).  A good test is to apply a sample ingress configuration  like https://github.com/yesinteractive/dadjokes/blob/master/examples/dadjokes_kong_for_k8s.yaml and then reload map)

**Comment by nikirago** [comment]
Issued was identified to be related to a trailing slash in the admin api configuration. Will update kongmap to trim trailing slashes. Re-labeled as a bug.

**Comment by nikirago** [comment]
Didn't have time to get this in but updated docs to note that admin api can not have trailing slash in the config.
